apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-info-depl
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: book-info-service
  template:
    metadata:
      labels:
        app: book-info-service
    spec:
      containers:
        - name: book-info-service
          image: niki241618/book-info-service
          env:
            - name: "AzureBlobStorage__ConnectionString"
              valueFrom: 
                secretKeyRef:
                  name: 'app-secrets'
                  key: 'AzureBlobStorage__ConnectionString'
            - name: "ConnectionStrings__DatabaseConnection"
              valueFrom: 
                secretKeyRef:
                  name: 'app-secrets'
                  key: 'ConnectionStrings__DatabaseConnection'
            - name: 'SeedDatabase'
              value: 'true'
#Declare the node port
---
apiVersion: v1
kind: Service
metadata:
  name: book-info-service-nodeport
spec:
  type: NodePort
  selector:
    app: book-info-service
  ports:
    - port: 80
      targetPort: 80