apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-service-depl
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: users-service
  template:
    metadata:
      labels:
        app: users-service
    spec:
      containers:
        - name: users-service
          image: niki241618/users-service
          resources:
            requests: #Claimed resources
              memory: "256Mi"
              cpu: "250m" #1/4 of the core
            limits:   #Maximum resources
              memory: "512Mi"
              cpu: "500m" #1/2 of the core
          env:
            - name: "AzureBlobStorage__ConnectionString"
              valueFrom: 
                secretKeyRef:
                  name: 'app-secrets'
                  key: 'AzureBlobStorage__ConnectionString'
            - name: "ConnectionStrings__DatabaseConnection"
              valueFrom: 
                secretKeyRef:
                  name: 'app-secrets'
                  key: 'ConnectionStrings__DatabaseConnection'
            - name: "Auth0__Domain"
              valueFrom: 
                secretKeyRef:
                  name: 'app-secrets'
                  key: 'Auth0__Domain'
            - name: "Auth0__Audience"
              valueFrom: 
                secretKeyRef:
                  name: 'app-secrets'
                  key: 'Auth0__Audience'
            - name: "Auth0__ClientId"
              valueFrom: 
                secretKeyRef:
                  name: 'app-secrets'
                  key: 'Auth0__ClientId'
            - name: "Auth0__ClientSecret"
              valueFrom: 
                secretKeyRef:
                  name: 'app-secrets'
                  key: 'Auth0__ClientSecret'
            - name: "Auth0__Management__ClientId"
              valueFrom: 
                secretKeyRef:
                  name: 'app-secrets'
                  key: 'Auth0__Management__ClientId'
            - name: "Auth0__Management__ClientSecret"
              valueFrom: 
                secretKeyRef:
                  name: 'app-secrets'
                  key: 'Auth0__Management__ClientSecret'
            - name: "ConnectionStrings__RabbitMqHostName"
              valueFrom:
                configMapKeyRef:
                  name: 'config'
                  key: 'RabbitMqHostName'
            - name: 'SeedDatabase'
              value: 'true'
#Declare the node port
---
apiVersion: v1
kind: Service
metadata:
  name: users-service-nodeport
spec:
  type: NodePort
  selector:
    app: users-service
  ports:
    - port: 80
      targetPort: 80
#Auto-Scaling
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: users-service-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: users-service-depl
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50